luffy_permission/luffy_permission/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^', include('web.urls')),
	url(r'^rbac/', include('rbac.urls', namespace='rbac')),
]

luffy_permission/rbac/urls.py
from django.conf.urls import url
from rbac import views

urlpatterns = [

	url(r'^role/list/$', views.role_list, name='role_list'),
	url(r'^role/add/$', views.role_change, name='role_add'),
	url(r'^role/edit/(\d+)/$', views.role_change, name='role_edit'),
	url(r'^role/del/(\d+)/$', views.role_del, name='role_del'),

	url(r'^menu/list/$', views.menu_list, name='menu_list'),
	url(r'^menu/add/$', views.menu_change, name='menu_add'),
	url(r'^menu/edit/(\d+)/$', views.menu_change, name='menu_edit'),
	# url(r'^menu/del/(\d+)/$', views.menu_del, name='menu_del'),

	url(r'^permission/add/$', views.permission_change, name='permission_add'),
	url(r'^permission/edit/(\d+)/$', views.permission_change, name='permission_edit'),

	url(r'^(menu|permission)/del/(\d+)/$', views.delete, name='delete'),
	# 批量操作权限
	url(r'^multi/permissions/$', views.multi_permissions, name='multi_permissions'),
	# 分配权限
	url(r'^distribute/permissions/$', views.distribute_permissions, name='distribute_permissions'),

]

luffy_permission/web/urls.py
from django.conf.urls import url
from web.views import customer
from web.views import payment
from web.views import auth

urlpatterns = [

    url(r'^login/$', auth.login,name='login'),
    url(r'^index/$', auth.index,name='index'),

    url(r'^customer/list/$', customer.customer_list,name='customer_list'),
    url(r'^customer/add/$', customer.customer_add,name='customer_add'),
    url(r'^customer/edit/(?P<cid>\d+)/$', customer.customer_edit,name='customer_edit'),
    url(r'^customer/del/(?P<cid>\d+)/$', customer.customer_del,name='customer_del'),

    url(r'^payment/list/$', payment.payment_list,name='payment_list'),
    url(r'^payment/add/$', payment.payment_add,name='payment_add'),
    url(r'^payment/edit/(?P<pid>\d+)/$', payment.payment_edit,name='payment_edit'),
    url(r'^payment/del/(?P<pid>\d+)/$', payment.payment_del,name='payment_del'),
]

luffy_permission/rbac/models.py
from django.db import models


class Menu(models.Model):
	title = models.CharField('菜单名称', max_length=32)
	icon = models.CharField('图标', max_length=64, blank=True, null=True)
	weight = models.IntegerField('权重',default=1)

	def __str__(self):
		return self.title

class Permission(models.Model):
	"""权限表
	二级菜单
	有menu_id     表示当前的权限是 二级菜单
	没有menu_id   表示当前的权限是 普通权限

	没有parent_id  表示当前的权限是 二级菜单
	有parent_id   表示当前的权限是 普通权限
	"""
	url = models.CharField('URL地址', max_length=108)
	title = models.CharField('标题', max_length=32)
	name = models.CharField('URL的别名',max_length=32,unique=True)
	menu = models.ForeignKey('Menu', blank=True, null=True,verbose_name='所属菜单')
	parent = models.ForeignKey('self', blank=True, null=True,verbose_name='父权限')

	# is_menu = models.BooleanField('是否是菜单', default=False)
	# icon = models.CharField('图标', max_length=64, blank=True, null=True)

	class Meta:
		verbose_name = '权限'
		verbose_name_plural = '所有权限'

	def __str__(self):
		return self.title


class Role(models.Model):
	"""角色表"""
	name = models.CharField('角色名称', max_length=32)
	permissions = models.ManyToManyField('Permission', verbose_name='角色所拥有的权限', blank=True)

	class Meta:
		verbose_name_plural = '所有角色'

	def __str__(self):
		return self.name


class User(models.Model):
	"""用户表"""
	name = models.CharField('用户名', max_length=32)
	pwd = models.CharField('密码', max_length=32)
	roles = models.ManyToManyField('Role', verbose_name='用户所拥有的角色', blank=True)

	class Meta:
		verbose_name_plural = '所有用户'

	def __str__(self):
		return self.name

luffy_permission/rbac/service/routes.py
from django.conf import settings
from django.utils.module_loading import import_string
from django.urls import RegexURLResolver, RegexURLPattern
from collections import OrderedDict


def recursion_urls(pre_namespace, pre_url, urlpatterns, url_ordered_dict):

    """

      None, "/",        [
                    url(r'^', include('web.urls')),
                    url(r'^rbac/', include('rbac.urls', namespace='rbac')),
                    ]

      None   "/^"

    """

    for item in urlpatterns:
        if isinstance(item, RegexURLResolver):
            if pre_namespace:
                if item.namespace:
                    namespace = "%s:%s" % (pre_namespace, item.namespace,)
                else:
                    namespace = pre_namespace
            else:
                if item.namespace:
                    namespace = item.namespace
                else:
                    namespace = None
            recursion_urls(namespace, pre_url + item.regex.pattern, item.url_patterns, url_ordered_dict)
        else:

            if pre_namespace:
                name = "%s:%s" % (pre_namespace, item.name,)
            else:
                name = item.name   # login
            if not item.name:
                raise Exception('URL路由中必须设置name属性')

            url = pre_url + item._regex  #   /login/

            url_ordered_dict[name] = {'name': name, 'url': url.replace('^', '').replace('$', '')}


def get_all_url_dict(ignore_namespace_list=None):
    """
    获取路由中
    :return:
    """
    ignore_list = ignore_namespace_list or []  # ignore_list  = ['admin']

    url_ordered_dict = OrderedDict()

    md = import_string(settings.ROOT_URLCONF)
    urlpatterns = []
    for item in md.urlpatterns:
        """
        [
            url(r'^', include('web.urls')),
            url(r'^rbac/', include('rbac.urls', namespace='rbac')),
        ]
        视图       RegexURLPattern 
        include    RegexURLResolver
        """
        if isinstance(item, RegexURLResolver) and item.namespace in ignore_list:
            continue
        urlpatterns.append(item)
    recursion_urls(None, "/", urlpatterns, url_ordered_dict)
    return url_ordered_dict

luffy_permission/rbac/views.py
from django.shortcuts import render, redirect, reverse, HttpResponse
from rbac import models
from rbac.forms import RoleForm, MenuForm, PermissionForm, MultiPermissionForm
from django.db.models import Q


def role_list(request):
	all_role = models.Role.objects.all()
	return render(request, 'rbac/role_list.html', {'all_role': all_role})


def role_change(request, edit_id=None):
	obj = models.Role.objects.filter(pk=edit_id).first()
	form_obj = RoleForm(instance=obj)
	if request.method == 'POST':
		form_obj = RoleForm(request.POST, instance=obj)
		if form_obj.is_valid():
			form_obj.save()
			return redirect(reverse('rbac:role_list'))

	return render(request, 'rbac/form.html', {'form_obj': form_obj})


def role_del(request, del_id):
	models.Role.objects.filter(pk=del_id).delete()
	return redirect(reverse('rbac:role_list'))


def menu_list(request):
	all_menu = models.Menu.objects.all()

	mid = request.GET.get('mid')

	if mid:
		all_permission = models.Permission.objects.filter(Q(menu_id=mid) | Q(parent__menu_id=mid)).values('id', 'url',
																										  'title',
																										  'name',
																										  'menu_id',
																										  'parent_id',
																										  'menu__title')

	else:
		all_permission = models.Permission.objects.all().values('id', 'url', 'title', 'name', 'menu_id', 'parent_id',
																'menu__title')

	"""
	{  id: {
			children : [ {} {} {} ]
		} ,
	  id: {
			
		}
	}	
	
	"""
	permission_dict = {}
	for i in all_permission:
		if i.get('menu_id'):
			i['children'] = []
			permission_dict[i['id']] = i

	for i in all_permission:
		pid = i.get('parent_id')
		if pid:
			permission_dict[pid]['children'].append(i)

	return render(request, 'rbac/menu_list.html',
				  {'mid': mid, 'all_menu': all_menu, 'all_permission': permission_dict.values()})


def menu_change(request, edit_id=None):
	obj = models.Menu.objects.filter(pk=edit_id).first()
	form_obj = MenuForm(instance=obj)
	if request.method == 'POST':
		form_obj = MenuForm(request.POST, instance=obj)
		if form_obj.is_valid():
			form_obj.save()
			return redirect(reverse('rbac:menu_list'))

	return render(request, 'rbac/form.html', {'form_obj': form_obj})


def permission_change(request, edit_id=None):
	obj = models.Permission.objects.filter(pk=edit_id).first()
	form_obj = PermissionForm(instance=obj)
	if request.method == 'POST':
		form_obj = PermissionForm(request.POST, instance=obj)
		if form_obj.is_valid():
			form_obj.save()
			return redirect(reverse('rbac:menu_list'))

	return render(request, 'rbac/form.html', {'form_obj': form_obj})


def delete(request, table, del_id):
	table_class = getattr(models, table.capitalize())
	table_class.objects.filter(pk=del_id).delete()
	return redirect('rbac:menu_list')


from django.forms import modelformset_factory, formset_factory
from rbac.service.routes import get_all_url_dict


# 批量操作权限
def multi_permissions(request):
	"""
	批量操作权限
	:param request:
	:return:
	"""
	post_type = request.GET.get('type')

	# 删除和编辑使用modelformset
	FormSet = modelformset_factory(models.Permission, MultiPermissionForm, extra=0)
	# 添加使用的formset
	AddFormSet = formset_factory(MultiPermissionForm, extra=0)

	# 获取数据中所有的权限
	permissions = models.Permission.objects.all()
	# 获取到路由系统所有的url（权限）
	router_dict = get_all_url_dict(ignore_namespace_list=['admin', 'rbac'])

	# 数据库中权限别名的集合
	permissions_name_set = set([i.name for i in permissions])
	# 路由系统中权限别名的集合
	router_name_set = set(router_dict.keys())
	# 新增权限的别名的集合
	add_name_set = router_name_set - permissions_name_set
	add_formset = AddFormSet(initial=[row for name, row in router_dict.items() if name in add_name_set])

	if request.method == 'POST' and post_type == 'add':
		add_formset = AddFormSet(request.POST)
		if add_formset.is_valid():
			permission_obj_list = [models.Permission(**i) for i in add_formset.cleaned_data]
			query_list = models.Permission.objects.bulk_create(permission_obj_list)
			add_formset = AddFormSet()
			for i in query_list:
				permissions_name_set.add(i.name)
	# 删除权限的别名的集合
	del_name_set = permissions_name_set - router_name_set
	del_formset = FormSet(queryset=models.Permission.objects.filter(name__in=del_name_set))

	# 更新权限的别名的集合
	update_name_set = permissions_name_set & router_name_set
	update_formset = FormSet(queryset=models.Permission.objects.filter(name__in=update_name_set))

	if request.method == 'POST' and post_type == 'update':
		update_formset = FormSet(request.POST)
		if update_formset.is_valid():
			update_formset.save()
			update_formset = FormSet(queryset=models.Permission.objects.filter(name__in=update_name_set))

	return render(
		request,
		'rbac/multi_permissions.html',
		{
			'del_formset': del_formset,
			'update_formset': update_formset,
			'add_formset': add_formset,
		}
	)


# 分配权限
def distribute_permissions(request):
	"""
	分配权限
	:param request:
	:return:
	"""
	uid = request.GET.get('uid')  # 用户的id
	rid = request.GET.get('rid')  # 角色的id

	if request.method == 'POST' and request.POST.get('postType') == 'role':
		user = models.User.objects.filter(id=uid).first()
		if not user:
			return HttpResponse('用户不存在')
		user.roles.set(request.POST.getlist('roles'))

	if request.method == 'POST' and request.POST.get('postType') == 'permission' and rid:
		role = models.Role.objects.filter(id=rid).first()
		if not role:
			return HttpResponse('角色不存在')
		role.permissions.set(request.POST.getlist('permissions'))

	# 所有用户
	user_list = models.User.objects.all()
	# 用户的角色的id
	user_has_roles = models.User.objects.filter(id=uid).values('id', 'roles')
	# 用户所拥有角色id的字典
	user_has_roles_dict = {item['roles']: None for item in user_has_roles}

	# 所有的角色
	role_list = models.Role.objects.all()

	if rid:
		role_has_permissions = models.Role.objects.filter(id=rid, permissions__id__isnull=False).values('id',
																										'permissions')
	elif uid and not rid:
		user = models.User.objects.filter(id=uid).first()
		if not user:
			return HttpResponse('用户不存在')
		role_has_permissions = user.roles.filter(permissions__id__isnull=False).values('id', 'permissions')
	else:
		role_has_permissions = []
	# 某一个角色所拥有的权限   某一个用户所拥有的所有的权限
	role_has_permissions_dict = {item['permissions']: None for item in role_has_permissions}
	# 所有菜单
	all_menu_list = []
	"""
	 all_menu_list =  [ 
	 	{ id  title  children :[
	 			{ 'id', 'title', 'menu_id'  'children' : [
	 				{'id', 'title', 'parent_id'}
	 			]   } 
	 	] }
	 	{'id': None, 'title': '其他', 'children': [
	 		{'id', 'title', 'parent_id'}
	 	]}
	 ]
	
	"""
	queryset = models.Menu.objects.values('id', 'title')  # 一级菜单的id 和 标题  [ { id  title } ]
	# 菜单的字典
	menu_dict = {}
	"""
	menu_dict = {
		一级菜单的id： { id  title  children :[
			{ 'id', 'title', 'menu_id'  'children' : [
					{'id', 'title', 'parent_id'}
				]   } 
		] },
		None: {'id': None, 'title': '其他', 'children': [
			{'id', 'title', 'parent_id'}
		]}
	}
	"""

	for item in queryset:  # { id  title }
		item['children'] = []  # { id  title  children :[]  }
		menu_dict[item['id']] = item
		all_menu_list.append(item)

	other = {'id': None, 'title': '其他', 'children': []}
	all_menu_list.append(other)
	menu_dict[None] = other
	# 二级菜单  父权限
	root_permission = models.Permission.objects.filter(menu__isnull=False).values('id', 'title', 'menu_id')

	root_permission_dict = {}
	"""
	root_permission_dict = {
			父权限的id： { 'id', 'title', 'menu_id'  'children' : [
				{'id', 'title', 'parent_id'}
			]   } 
	}
	"""

	for per in root_permission:  # { 'id', 'title', 'menu_id' }
		per['children'] = []  # { 'id', 'title', 'menu_id'  'children' : []   }
		nid = per['id']
		menu_id = per['menu_id']
		root_permission_dict[nid] = per
		menu_dict[menu_id]['children'].append(per)

	node_permission = models.Permission.objects.filter(menu__isnull=True).values('id', 'title', 'parent_id')

	for per in node_permission:  # {'id', 'title', 'parent_id'}
		pid = per['parent_id']
		if not pid:
			menu_dict[None]['children'].append(per)
			continue
		root_permission_dict[pid]['children'].append(per)

	return render(
		request,
		'rbac/distribute_permissions.html',
		{
			'user_list': user_list,  # 所有的用户
			'role_list': role_list,  # 所有的角色
			'user_has_roles_dict': user_has_roles_dict,  # 当前用户所拥有的角色
			'role_has_permissions_dict': role_has_permissions_dict,  # 某一个角色所拥有的权限   某一个用户所拥有的所有的权限
			'all_menu_list': all_menu_list,  # 所有的菜单信息 父权限 子权限  普通的权限
			'uid': uid,
			'rid': rid
		}
	)

luffy_permission/rbac/templates/rbac/breadcrumb.html
<ol class="breadcrumb no-radius no-margin" style="border-bottom: 1px solid #ddd;">
    {% for breadcrumb in breadcrumb_list %}
        {% if forloop.last %}
            <li class="active">{{ breadcrumb.title }}</li>
        {% else %}
            <li><a href="{{ breadcrumb.url }}">{{ breadcrumb.title }}</a></li>
        {% endif %}
    {% endfor %}
</ol>

luffy_permission/rbac/templates/rbac/form.html
{% extends 'layout.html' %}

{% block css %}
    <style>

        .icon-area ul {
            list-style-type: none;
            padding: 0;
        }

        .icon-area ul li {
            float: left;
            padding: 10px;
            padding-left: 0;
            width: 80px;
        }

        .icon-area ul li i {
            font-size: 18px;
            margin-left: 5px;
            color: #6d6565;
        }

    </style>

{% endblock %}

{% block content %}

    <div class="col-lg-offset-1 col-lg-8" style="margin-top: 50px">

        <form class="form-horizontal" action="" method="post" novalidate>
            {% csrf_token %}
            {% for field in form_obj %}
                <div class="form-group {% if field.errors %} has-error{% endif %}">

                    <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                    <div class="col-sm-10 icon-area">
                        {{ field }}
                        <span id="helpBlock2" class="help-block">{{ field.errors.0 }}</span>
                    </div>
                </div>
            {% endfor %}
            <p class="text-danger text-center"> {{ form_obj.non_field_errors.0 }} </p>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">保存</button>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

luffy_permission/rbac/templates/rbac/menu.html
{#<div class="static-menu">#}
{##}
{#    {% for menu in menu_list %}#}
{#        <a href="{{ menu.url }}"  class="{{ menu.class }}" >#}
{#            <span class="icon-wrap"><i class="fa {{ menu.icon }}"></i></span> {{ menu.title }}</a>#}
{#    {% endfor %}#}
{##}
{#</div>#}


<div class="multi-menu">
    {% for menu in  menu_list %}
        <div class="item">
            <div class="title"> &nbsp;<i class="fa {{ menu.icon }}"></i> &nbsp;{{ menu.title }}</div>
            <div class="body {{ menu.class }}">
                {% for child in menu.children %}
                    <a  class="{{ child.class }}" href="{{ child.url }}"> {{ child.title }} </a>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
</div>

luffy_permission/rbac/templates/rbac/menu_list.html
{% extends 'layout.html' %}

{% block css %}
    <style>

        .permission-area tr.root {
            background-color: #a6fdfd;;
        }

        .menu-body tr.active {
            background-color: #f1f7fd;
            border-left: 3px solid #fdc00f;
        }

    </style>
{% endblock %}
{% block content %}
    <div style="margin-top: 20px">

        <div class="col-lg-3">
            <div class="panel panel-default">
                <div class="panel-heading"><i class="fa fa-book"></i> 菜单管理
                    <a style="padding: 2px 7px;margin-top: -2px" href="{% url 'rbac:menu_add' %}"
                       class="btn btn-sm btn-success pull-right"> <i
                            class="fa fa-plus"></i> 添加</a>
                </div>

                <table class="table  table-hover">
                    <thead>
                    <tr>
                        <th>名称</th>
                        <th>图标</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody class="menu-body">
                    {% for menu in all_menu %}
                        <tr class="{% if mid == menu.pk|safe %} active{% endif %}">
                            <td><a href="?mid={{ menu.pk }}">{{ menu.title }}</a></td>
                            <td><i class="fa {{ menu.icon }}"></i></td>
                            <td><a href="{% url 'rbac:menu_edit' menu.pk %}"> <i class="fa fa-edit"></i> </a>
                                <a href="{% url 'rbac:delete' 'menu' menu.pk %}"> <i class="fa fa-trash-o"></i> </a>
                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>

            </div>
        </div>

        <div class="col-lg-9">
            <div class="panel panel-default">
                <div class="panel-heading"><i class="fa fa-cubes"></i> 权限管理
                    <a style="padding: 2px 7px;margin-top: -2px" href="{% url 'rbac:multi_permissions' %}" class="btn btn-sm btn-primary pull-right"> <i
                            class="fa fa-mail-forward"></i> 批量操作</a>
                    <a style="padding: 2px 7px;margin-top: -2px" href="{% url 'rbac:permission_add' %}" class="btn btn-sm btn-success pull-right"> <i
                            class="fa fa-plus-circle"></i> 新建</a>

                </div>
                <table class="table  table-hover">
                    <thead>
                    <tr>
                        <th>名称</th>
                        <th>URL</th>
                        <th>URL别名</th>
                        <th>所属菜单</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody class="permission-area">
                    {% for p_permission in all_permission %}
                        <tr class="root">
                            <td class="title" id="{{ p_permission.id }}"><i
                                    class="fa fa-caret-down"></i> {{ p_permission.title }}</td>
                            <td>{{ p_permission.url }}</td>
                            <td>{{ p_permission.name }}</td>
                            <td>{{ p_permission.menu__title }}</td>
                            <td><a href="{% url 'rbac:permission_edit' p_permission.id %}"> <i class="fa fa-edit"></i> </a>
                                <a href="{% url 'rbac:delete' 'permission' p_permission.id %}"> <i class="fa fa-trash-o"></i> </a>
                            </td>
                        </tr>

                        {% for c_permission in p_permission.children %}
                            <tr pid="{{ p_permission.id }}">
                                <td>{{ c_permission.title }}</td>
                                <td>{{ c_permission.url }}</td>
                                <td>{{ c_permission.name }}</td>
                                <td></td>
                                <td><a href="{% url 'rbac:permission_edit' c_permission.id %}"> <i class="fa fa-edit"></i> </a>
                                    <a href="{% url 'rbac:delete' 'permission' c_permission.id %}"> <i class="fa fa-trash-o"></i> </a>
                                </td>
                            </tr>
                        {% endfor %}



                    {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>



{% endblock %}


{% block js %}

    <script>
        $('.permission-area tr td.title').click(function () {
            pid = $(this).attr('id');
            caret = $(this).find('i');
            if (caret.hasClass('fa-caret-down')) {
                caret.removeClass('fa-caret-down').addClass('fa-caret-right');
            } else {
                caret.removeClass('fa-caret-right').addClass('fa-caret-down');
            }
            tr = $(this).parent().nextAll("[pid=" + pid + "]");
            tr.toggleClass('hide')

        })

    </script>

{% endblock %}

luffy_permission/rbac/templates/rbac/multi_permissions.html
{% extends 'layout.html' %}

{% block content %}
    <div class="luffy-container">
        <form method="post" action="?type=add">
            {% csrf_token %}
            {{ add_formset.management_form }}
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <i class="fa fa-binoculars" aria-hidden="true"></i> 待新建权限列表
                    <button class="right btn btn-primary btn-xs" style="padding: 2px 8px;margin: -3px;">
                        <i class="fa fa-save" aria-hidden="true"></i>
                        新建
                    </button>
                </div>
                <div class="panel-body" style="color: #9d9d9d;">
                    注意：路由系统中自动发现且数据库中不存在的路由。
                </div>

                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>名称</th>
                        <th>URL</th>
                        <th>别名</th>
                        <th>父权限</th>
                        <th>所属菜单</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for form in add_formset %}

                        <tr>
                            <td style="vertical-align: middle;">{{ forloop.counter }}</td>
                            <td>{{ form.title }} <span>{{ form.title.errors.0 }}</span></td>
                            <td>{{ form.url }}</td>
                            <td>{{ form.name }}</td>
                            <td>{{ form.parent }}</td>
                            <td>{{ form.menu }}</td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </form>

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <i class="fa fa-th-list" aria-hidden="true"></i> 待删除权限列表
            </div>
            <div class="panel-body" style="color: #9d9d9d;">
                注意：数据库中存在，但路由系统中不存在的路由。
            </div>

            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>序号</th>
                    <th>名称</th>
                    <th>URL</th>
                    <th>别名</th>
                    <th>父权限</th>
                    <th>所属菜单</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for form in del_formset %}

                    <tr>
                        {{ form.id }}

                        <td style="vertical-align: middle;">{{ forloop.counter }}</td>
                        <td>{{ form.title }} <span>{{ form.title.errors.0 }}</span></td>
                        <td>{{ form.url }}</td>
                        <td>{{ form.name }}</td>
                        <td>{{ form.parent }}</td>
                        <td>{{ form.menu }}</td>
                        <td>
                            <a href="{% url 'rbac:delete' 'permission' form.id.value %}" style="color:#d9534f;">
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <form method="post" action="?type=update">
            {% csrf_token %}
            {{ update_formset.management_form }}
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <i class="fa fa-sitemap" aria-hidden="true"></i> 待更新权限列表
                    <button class="right btn btn-primary btn-xs" style="padding: 2px 8px;margin: -3px;">
                        <i class="fa fa-save" aria-hidden="true"></i>
                        更新
                    </button>
                </div>
                <div class="panel-body" style="color: #9d9d9d;">
                    注意：数据库和路由系统都存在的路由。
                </div>

                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>名称</th>
                        <th>URL</th>
                        <th>别名</th>
                        <th>父权限</th>
                        <th>所属菜单</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for form in update_formset %}
                        <tr>
                            {{ form.id }}
                            <td style="vertical-align: middle;">{{ forloop.counter }}</td>
                            <td>{{ form.title }} <span>{{ form.title.errors.0 }}</span></td>
                            <td>{{ form.url }}</td>
                            <td>{{ form.name }}</td>
                            <td>{{ form.parent }}</td>
                            <td>{{ form.menu }}</td>
                            <td>
                                <a href="{% url 'rbac:delete' 'permission' form.id.value %}" style="color:#d9534f;">
                                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </form>
    </div>
{% endblock %}

luffy_permission/rbac/templates/rbac/role_list.html
{% extends 'layout.html' %}

{% block content %}
    <h3>角色管理</h3>
    <a class="btn btn-primary btn-sm" href="{% url 'rbac:role_add' %}">添加</a>
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th>序号</th>
            <th>名称</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for role in all_role %}
            <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ role.name }}</td>
            <td>
                <a href="{% url 'rbac:role_edit' role.pk %}"> <i class="fa fa-edit"></i> </a>
                <a href="{% url 'rbac:role_del' role.pk %}"> <i class="fa fa-trash-o"></i> </a>
            </td>
            </tr>

        {% endfor %}

        </tbody>
    </table>
{% endblock %}