ob_crm/crm/urls.py
from django.conf.urls import url, include
from crm.views import auth
from crm.views import customer,teacher

urlpatterns = [
	url(r'^login/$', auth.login, name='login'),
	url(r'^index/$', auth.index, name='index'),
	url(r'^reg/$', auth.reg, name='reg'),

	# 公户
	url(r'^customer_list/$', customer.CustomerList.as_view(), name='customer_list'),
	# 私户
	url(r'^my_customer/$', customer.CustomerList.as_view(), name='my_customer'),

	# url(r'^add_customer/', customer.add_customer, name='add_customer'),
	# url(r'^edit_customer/(\d+)/', customer.edit_customer, name='edit_customer'),
	url(r'^add_customer/$', customer.customer_change, name='add_customer'),
	url(r'^edit_customer/(\d+)/$', customer.customer_change, name='edit_customer'),

	# 跟进记录的展示   某个销售的所有客户的跟进记录
	url(r'^consult_list/$', customer.ConsultList.as_view(), name='consult_list'),

	# 跟进记录的展示   某个客户的所有跟进记录
	url(r'^consult_list/(\d+)/$', customer.ConsultList.as_view(), name='one_consult_list'),

	# 添加跟进
	url(r'^add_consult/$', customer.add_consult, name='add_consult'),
	# 编辑跟进
	url(r'^edit_consult/(\d+)/$', customer.edit_consult, name='edit_consult'),

	url(r'^enrollment_list/$', customer.EnrollmentList.as_view(), name='enrollment_list'),

	# 添加报名表
	url(r'^add_enrollment/(?P<customer_id>\d+)$', customer.enrollment_change, name='add_enrollment'),
	# 编辑报名表
	url(r'^edit_enrollment/(?P<edit_id>\d+)/$', customer.enrollment_change, name='edit_enrollment'),

	# 班级的展示
	url(r'^class_list/$', teacher.ClassList.as_view(), name='class_list'),

	# 添加班级
	url(r'^add_class/$', teacher.class_change, name='add_class'),
	# 编辑班级
	url(r'^edit_class/(?P<edit_id>\d+)/$', teacher.class_change, name='edit_class'),

	# 展示某个班级的课程记录
	url(r'^course_record_list/(?P<class_id>\d+)$', teacher.CourseRecordList.as_view(), name='course_record_list'),

	# 添加课程记录
	url(r'^add_course_record/(?P<class_id>\d+)/$', teacher.course_record_change, name='add_course_record'),
	# 编辑课程记录
	url(r'^edit_course_record/(?P<edit_id>\d+)/$', teacher.course_record_change, name='edit_course_record'),


	# 展示某个课程记录的学习记录
	url(r'^study_record_list/(?P<course_record_id>\d+)$', teacher.study_record_list, name='study_record_list'),


]

ob_crm/ob_crm/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from crm import page_view
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^crm/',include('crm.urls')),
    url(r'^rbac/',include('rbac.urls',namespace='rbac')),

    # url(r'^user_list/',page_view.user_list),


]

ob_crm/crm/models.py
from django.db import models
from multiselectfield import MultiSelectField
from django.utils.safestring import mark_safe
from rbac.models import User
course_choices = (('Linux', 'Linux中高级'),
				  ('PythonFullStack', 'Python高级全栈开发'),)

class_type_choices = (('fulltime', '脱产班',),
					  ('online', '网络班'),
					  ('weekend', '周末班',),)

source_type = (('qq', "qq群"),
			   ('referral', "内部转介绍"),
			   ('website', "官方网站"),
			   ('baidu_ads', "百度推广"),
			   ('office_direct', "直接上门"),
			   ('WoM', "口碑"),
			   ('public_class', "公开课"),
			   ('website_luffy', "路飞官网"),
			   ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
						 ('unregistered', "未报名"),
						 ('studying', '学习中'),
						 ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
					   ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)
pay_type_choices = (('deposit', "订金/报名费"),
					('tuition', "学费"),
					('transfer', "转班"),
					('dropout', "退学"),
					('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
					  ('vacate', "请假"),
					  ('late', "迟到"),
					  ('absence', "缺勤"),
					  ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
				 (90, 'A'),
				 (85, 'B+'),
				 (80, 'B'),
				 (70, 'B-'),
				 (60, 'C+'),
				 (50, 'C'),
				 (40, 'C-'),
				 (0, ' D'),
				 (-1, 'N/A'),
				 (-100, 'COPY'),
				 (-1000, 'FAIL'),)


class Department(models.Model):
	"""
	部门表
	"""
	name = models.CharField(max_length=32, verbose_name="部门名称")
	count = models.IntegerField(verbose_name="人数", default=0)

	def __str__(self):
		return self.name


class UserProfile(User):
	"""
	用户表
	"""
	username = models.EmailField(max_length=255, unique=True, )
	password = models.CharField(max_length=128)
	name = models.CharField('名字', max_length=32)
	department = models.ForeignKey('Department', default=None, blank=True, null=True)
	mobile = models.CharField('手机', max_length=32, default=None, blank=True, null=True)
	memo = models.TextField('备注', blank=True, null=True, default=None)
	date_joined = models.DateTimeField(auto_now_add=True)
	is_active = models.BooleanField(default=True)

	def __str__(self):
		return self.name


class Customer(models.Model):
	"""
	客户表
	"""
	qq = models.CharField('QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
	qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
	name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名')
	sex_type = (('male', '男'), ('female', '女'))
	sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True)
	birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)
	phone = models.BigIntegerField('手机号', blank=True, null=True)
	source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')
	introduce_from = models.ForeignKey('self', verbose_name="转介绍自学员", blank=True, null=True)
	course = MultiSelectField("咨询课程", choices=course_choices)
	class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
	customer_note = models.TextField("客户备注", blank=True, null=True, )
	status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",
							  help_text="选择客户此时的状态")
	last_consult_date = models.DateField("最后跟进日期", auto_now_add=True)
	next_date = models.DateField("预计再次跟进时间", blank=True, null=True)
	consultant = models.ForeignKey('UserProfile', verbose_name="销售", related_name='customers', blank=True, null=True, )
	class_list = models.ManyToManyField('ClassList', verbose_name="已报班级", blank=True)

	def __str__(self):
		return "{} - {}".format(self.qq, self.name)

	def show_classes(self):
		return ' | '.join([str(i) for i in self.class_list.all()])

	def show_status(self):
		"""
		(('signed', "已报名"),
		 ('unregistered', "未报名"),
		 ('studying', '学习中'),
		 ('paid_in_full', "学费已交齐"))
		"""
		color_dict = {
			'signed': '#31b731',
			'unregistered': 'red',
			'studying': 'blue',
			'paid_in_full': 'yellow',
		}

		return mark_safe(
			'<span style="background-color: {};color: white;padding: 4px">{}</span>'.format(color_dict.get(self.status),
																							self.get_status_display()))


class Campuses(models.Model):
	"""
	校区表
	"""
	name = models.CharField(verbose_name='校区', max_length=64)
	address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

	def __str__(self):
		return self.name


class ClassList(models.Model):
	"""
	班级表
	"""
	course = models.CharField("课程名称", max_length=64, choices=course_choices)
	semester = models.IntegerField("学期")
	campuses = models.ForeignKey('Campuses', verbose_name="校区")
	price = models.IntegerField("学费", default=10000)
	memo = models.CharField('说明', blank=True, null=True, max_length=100)
	start_date = models.DateField("开班日期")
	graduate_date = models.DateField("结业日期", blank=True, null=True)
	teachers = models.ManyToManyField('UserProfile', verbose_name="老师")
	class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True,
								  null=True)

	class Meta:
		unique_together = ("course", "semester", 'campuses')

	def __str__(self):
		return "{} - {} ({})".format(self.get_course_display(), self.semester, self.campuses.name)

	def show_teachers(self):
		return ' | '.join([ str(i) for i in self.teachers.all()])

class ConsultRecord(models.Model):
	"""
	跟进记录表
	"""
	customer = models.ForeignKey('Customer', verbose_name="所咨询客户")
	note = models.TextField(verbose_name="跟进内容...")
	status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")
	consultant = models.ForeignKey("UserProfile", verbose_name="跟进人", related_name='records')
	date = models.DateTimeField("跟进日期", auto_now_add=True)
	delete_status = models.BooleanField(verbose_name='删除状态', default=False)


class Enrollment(models.Model):
	"""
	报名表
	"""

	why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)
	your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)
	contract_agreed = models.BooleanField("我已认真阅读完培训协议并同意全部协议内容", default=False)
	contract_approved = models.BooleanField("审批通过", help_text="在审阅完学员的资料无误后勾选此项,合同即生效", default=False)
	enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")
	memo = models.TextField('备注', blank=True, null=True)
	delete_status = models.BooleanField(verbose_name='删除状态', default=False)
	customer = models.ForeignKey('Customer', verbose_name='客户名称')
	school = models.ForeignKey('Campuses')
	enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级")

	class Meta:
		unique_together = ('enrolment_class', 'customer')


class PaymentRecord(models.Model):
	"""
	缴费记录表
	"""
	pay_type = models.CharField("费用类型", choices=pay_type_choices, max_length=64, default="deposit")
	paid_fee = models.IntegerField("费用数额", default=0)
	note = models.TextField("备注", blank=True, null=True)
	date = models.DateTimeField("交款日期", auto_now_add=True)
	course = models.CharField("课程名", choices=course_choices, max_length=64, blank=True, null=True, default='N/A')
	class_type = models.CharField("班级类型", choices=class_type_choices, max_length=64, blank=True, null=True,
								  default='N/A')
	enrolment_class = models.ForeignKey('ClassList', verbose_name='所报班级', blank=True, null=True)
	customer = models.ForeignKey('Customer', verbose_name="客户")
	consultant = models.ForeignKey('UserProfile', verbose_name="销售")
	delete_status = models.BooleanField(verbose_name='删除状态', default=False)

	status_choices = (
		(1, '未审核'),
		(2, '已审核'),
	)
	status = models.IntegerField(verbose_name='审核', default=1, choices=status_choices)

	confirm_date = models.DateTimeField(verbose_name="确认日期", null=True, blank=True)
	confirm_user = models.ForeignKey(verbose_name="确认人", to='UserProfile', related_name='confirms', null=True,
									 blank=True)


class CourseRecord(models.Model):
	"""课程记录表"""
	day_num = models.IntegerField("节次", help_text="此处填写第几节课或第几天课程...,必须为数字")
	date = models.DateField(auto_now_add=True, verbose_name="上课日期")
	course_title = models.CharField('本节课程标题', max_length=64, blank=True, null=True)
	course_memo = models.TextField('本节课程内容', max_length=300, blank=True, null=True)
	has_homework = models.BooleanField(default=True, verbose_name="本节有作业")
	homework_title = models.CharField('本节作业标题', max_length=64, blank=True, null=True)
	homework_memo = models.TextField('作业描述', max_length=500, blank=True, null=True)
	scoring_point = models.TextField('得分点', max_length=300, blank=True, null=True)
	re_class = models.ForeignKey('ClassList', verbose_name="班级")
	teacher = models.ForeignKey('UserProfile', verbose_name="讲师", related_name='t_course_records')
	recorder = models.ForeignKey('UserProfile', verbose_name="记录者", related_name='r_course_records')

	class Meta:
		unique_together = ('re_class', 'day_num')

	def __str__(self):
		return "{}- day{}".format(self.re_class,self.day_num)

class StudyRecord(models.Model):
	"""
	学习记录
	"""

	attendance = models.CharField("考勤", choices=attendance_choices, default="checked", max_length=64)
	score = models.IntegerField("本节成绩", choices=score_choices, default=-1)
	homework_note = models.CharField(max_length=255, verbose_name='作业批语', blank=True, null=True)
	date = models.DateTimeField(auto_now_add=True)
	note = models.CharField("备注", max_length=255, blank=True, null=True)
	homework = models.FileField(verbose_name='作业文件', blank=True, null=True, default=None)
	course_record = models.ForeignKey('CourseRecord', verbose_name="某节课程")
	student = models.ForeignKey('Customer', verbose_name="学员")

	class Meta:
		unique_together = ('course_record', 'student')

ob_crm/crm/views/teacher.py
from django.shortcuts import render, HttpResponse, redirect, reverse
from crm import models
from crm.forms import ClassListForm, CourseRecordForm, StudyRecordForm
from utils.pagination import Pagination
from django.views import View
from django.db.models import Q


class BaseView(View):

    def post(self, request, *args, **kwargs):

        action = request.POST.get('action')

        if hasattr(self, action):
            response = getattr(self, action)()
            if response:
                return response
        else:
            return HttpResponse('非法操作')

        return self.get(request, *args, **kwargs)

    def search(self, filed_list):
        query = self.request.GET.get('query', '')
        q = Q()
        q.connector = 'OR'
        for field_name in filed_list:
            q.children.append(Q(('{}__contains'.format(field_name), query)))

        return q


class ClassList(BaseView):
    def get(self, request, *args, **kwargs):
        q = self.search([])

        all_class = models.ClassList.objects.filter(q)

        # 分页
        page = Pagination(request.GET.get('page', '1'), all_class.count(), request.GET.copy(), 2)

        # 返回页面
        return render(request, 'teacher/class_list.html',
                      {'all_class': all_class[page.start:page.end], 'page_html': page.page_html})


# 添加和编辑班级
def class_change(request, edit_id=None):
    obj = models.ClassList.objects.filter(pk=edit_id).first()
    form_obj = ClassListForm(instance=obj)
    title = '编辑班级' if edit_id else '添加班级'

    if request.method == 'POST':
        form_obj = ClassListForm(request.POST, instance=obj)
        if form_obj.is_valid():
            form_obj.save()
            next = request.GET.get('next')
            return redirect(next)

    return render(request, 'form.html', {'form_obj': form_obj, 'title': title})


# 展示课程记录
class CourseRecordList(BaseView):
    def get(self, request, *args, class_id, **kwargs):
        q = self.search([])

        all_course_record = models.CourseRecord.objects.filter(q, re_class_id=class_id)

        page = Pagination(request.GET.get('page', '1'), all_course_record.count(), request.GET.copy(), 2)

        # 返回页面
        return render(request, 'teacher/course_record_list.html',
                      {'all_course_record': all_course_record[page.start:page.end],
                       'page_html': page.page_html,
                       'class_id': class_id
                       })

    def multi_init(self):
        # 批量初始化学习记录
        course_record_ids = self.request.POST.get('ids', [])

        for course_record_id in course_record_ids:
            # 根据一个课程ID生成学习记录
            course_record_obj = models.CourseRecord.objects.filter(pk=course_record_id).first()
            # 找当前班级的所有学生
            students = course_record_obj.re_class.customer_set.filter(status='studying')

            # for student in students:
            # 	models.StudyRecord.objects.get_or_create(student=student,course_record_id=course_record_id)
            # 	models.StudyRecord.objects.update_or_create(student=student,course_record_id=course_record_id)

            # 批量插入
            study_record_list = []
            for student in students:
                if not models.StudyRecord.objects.filter(student=student, course_record_id=course_record_id).exists():
                    study_record_list.append(models.StudyRecord(student=student, course_record_id=course_record_id))

            models.StudyRecord.objects.bulk_create(study_record_list)


# 添加和编辑课程记录
def course_record_change(request, class_id=None, edit_id=None):
    obj = models.CourseRecord(re_class_id=class_id,
                              recorder=request.user_obj) if class_id else models.CourseRecord.objects.filter(
        pk=edit_id).first()
    form_obj = CourseRecordForm(instance=obj)
    title = '添加课程记录' if class_id else '编辑课程记录'
    if request.method == 'POST':
        form_obj = CourseRecordForm(request.POST, instance=obj)
        if form_obj.is_valid():
            form_obj.save()
            next = request.GET.get('next')
            return redirect(next)

    return render(request, 'form.html', {'form_obj': form_obj, 'title': title})


from django.forms import modelformset_factory


# 展示和编辑学习记录
def study_record_list(request, course_record_id):
    FormSet = modelformset_factory(models.StudyRecord, form=StudyRecordForm, extra=0)  # 生产modelformset的类
    formset_obj = FormSet(queryset=models.StudyRecord.objects.filter(course_record_id=course_record_id))

    if request.method == 'POST':
        formset_obj = FormSet(data=request.POST)
        if formset_obj.is_valid():
            formset_obj.save()

    return render(request, 'teacher/study_record_list.html', {'formset_obj': formset_obj})

ob_crm/crm/templates/teacher/class_list.html
{% extends 'layout.html' %}


{% block content %}
    {% load my_tags %}
    {% load rbac %}
    <div>
        {% if request|has_permission:'add_class' %}
            <a class="btn btn-primary" href="{% reverse_url request 'add_class' %}">添加</a>
        {% endif %}
    </div>

    <form action="" class="form-inline pull-right">
        <input type="text" name="query" class="form-control">
        <button class="btn btn-sm btn-primary">搜索</button>
    </form>

    <form action="" method="post" class="form-inline">
        {% csrf_token %}
        {#        <select name="action" id="" class="form-control">#}
        {##}
        {#        </select>#}
        {#        <button class="btn btn-primary btn-sm">提交</button>#}

        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>选择</th>
                <th>序号</th>
                <th>名称</th>
                <th>学费</th>
                <th>说明</th>
                <th>开班日期</th>
                <th>结业日期</th>
                <th>老师</th>
                <th>班级类型</th>
                {% if request|has_permission:'edit_class' %}
                    <th>操作</th>
                {% endif %}
            </tr>
            </thead>
            <tbody>

            {% for class_obj in all_class %}
                <tr>
                    <td><input type="checkbox" name="ids" value="{{ class_obj.pk }}"></td>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'course_record_list' class_obj.pk %}">{{ class_obj }}</a></td>
                    <td>{{ class_obj.price }}</td>
                    <td>{{ class_obj.memo }}</td>
                    <td>{{ class_obj.start_date }}</td>
                    <td>{{ class_obj.graduate_date }}</td>
                    <td>{{ class_obj.show_teachers }}</td>
                    <td>{{ class_obj.get_class_type_display }}</td>
                    {% if request|has_permission:'edit_class' %}

                        <td><a href="{% reverse_url request 'edit_class' class_obj.pk %}"> <i
                                class="fa fa-edit"></i></a>
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </form>

    <nav aria-label="Page navigation">
        <ul class="pagination">
            {{ page_html|safe }}
        </ul>
    </nav>

{% endblock %}

ob_crm/crm/templates/teacher/course_record_list.html
{% extends 'layout.html' %}


{% block content %}
    {% load my_tags %}

    <div>
        <a class="btn btn-primary" href="{% reverse_url request 'add_course_record' class_id %}">添加</a>
    </div>

    <form action="" class="form-inline pull-right">
        <input type="text" name="query" class="form-control">
        <button class="btn btn-sm btn-primary">搜索</button>
    </form>

    <form action="" method="post" class="form-inline">
        {% csrf_token %}
        <select name="action" id="" class="form-control">
            <option value="multi_init">批量初始化学习记录</option>
        </select>
        <button class="btn btn-primary btn-sm">提交</button>

        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>选择</th>
                <th>序号</th>
                <th>名称</th>
                <th>日期</th>
                <th>课程标题</th>
                <th>课程内容</th>
                <th>是否有作业</th>
                <th>讲师</th>
                <th>记录者</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>

            {% for course_record in all_course_record %}
                <tr>
                    <td><input type="checkbox" name="ids" value="{{ course_record.pk }}"></td>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'study_record_list' course_record.pk %}">{{ course_record }}</a>  </td>
                    <td>{{ course_record.date }}</td>
                    <td>{{ course_record.course_title }}</td>
                    <td>{{ course_record.course_memo }}</td>
                    <td>{{ course_record.has_homework }}</td>
                    <td>{{ course_record.teacher }}</td>
                    <td>{{ course_record.recorder }}</td>
                    <td><a href="{% reverse_url request 'edit_course_record' course_record.pk  %}"> <i class="fa fa-edit"></i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </form>

    <nav aria-label="Page navigation">
        <ul class="pagination">
            {{ page_html|safe }}
        </ul>
    </nav>

{% endblock %}

ob_crm/crm/templates/teacher/study_record_list.html
{% extends 'layout.html' %}


{% block content %}
    {% load my_tags %}



    <form action="" method="post" class="form-inline">
        {% csrf_token %}
        {{ formset_obj.management_form }}

        <table class="table table-bordered table-hover">
            <thead>
            <tr>

                <th>序号</th>
                <th>学生姓名</th>
                <th>考勤</th>
                <th>成绩</th>
                <th>作业批语</th>

            </tr>
            </thead>
            <tbody>

            {% for form in formset_obj %}
                <tr>
                    {{ form.id }}
                    <td>{{ forloop.counter }}</td>
                    <td>{{ form.instance.student }}</td>
                    <td>{{ form.attendance }}</td>
                    <td>{{ form.score }}</td>
                    <td>{{ form.homework_note }}</td>
                    <td class="hidden">{{ form.student }}</td>
                    <td class="hidden">{{ form.course_record }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <button class="btn btn-sm btn-primary">保存</button>
    </form>

    <nav aria-label="Page navigation">
        <ul class="pagination">
            {{ page_html|safe }}
        </ul>
    </nav>

{% endblock %}